version: '3.3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ag_demo
      POSTGRES_DB: ag_demo
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  app:
    depends_on:
      - db
    image: sha256:2b414450460dbcde4eb59127ed37ec9881e5b022035d41f972c234c89474a33b
    ports:
      - 8000:8080
    environment:
      DB_HOST: db:5432
      DB_USER: ga_demo
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

secrets:
  db_password:
    external:
      name: ga_demo_postgres_password
